### ISSUE TITLE
correction and Error Reporting

### ISSUE THREAD

**Issue by sangsang-choi** [karma22/PCArtco#2]
correction : [참고 Video01] 영문을 중문으로 수정해 주세요.  This item is already in use ---  素材正在使用中

Error : [참고  Video02] 소리블록 사용시 사용자가 녹음한 음성파일을 사용해서 프로젝트를 저장하고, 다시 그 프로젝트를 불러오면 녹음된 파일의 이름도 바뀌러 있고 재생이 되지않음.  (선생님 소리블록에 영문으로 표기되는 이름을 중문으로 보이도록 이 부분도 수정 부탁드립니다.)

**Comment by karma22** [comment]
오늘 저녁 중에 처리하겠습니다
